version: '3'
services:
  vuecli:
    image: "{{cookiecutter.project_name}}-vue2"
    networks:
      - "{{cookiecutter.project_name}}_network"
    build:
      context: "./frontend"
    volumes:
      - "./frontend/src:/app/src"
      - "./frontend/tsconfig.json:/app/tsconfig.json"
      - "./frontend/.eslintrc.js:/app/.eslintrc.js"
      - "./frontend/.browserslistrc:/app/.browserslistrc"
      - "./frontend/babel.config.js:/app/babel.config.js"
      # - "./frontend/webpack.config.js:/app/webpack.config.js"
      - "./frontend/vue.config.js:/app/vue.config.js"
    ports:
      - "{{ cookiecutter.dev_front_end_port }}:8080"
    command: "npm run serve"

  
networks:
  {{cookiecutter.project_name}}_network:
    driver: bridge
